document.writeln("<footer class=\'main-footer\'>");
document.writeln("");
document.writeln("  <!--Widgets Section-->");
document.writeln("  <div class=\'widgets-section\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'row\'>");
document.writeln("");
document.writeln("");
document.writeln("            <!--Footer Column-->");
document.writeln("            <div class=\'footer-column col-lg-4 col-md-6 col-sm-6 col-xs-12\'>");
document.writeln("              <div class=\'footer-widget about-widget\'>");
document.writeln("                <h3 class=\'footer-title\'>公司介绍</h3>");
document.writeln("");
document.writeln("                <div class=\'widget-content\'>");
document.writeln("                  <div class=\'text\'><p>The Experts consulting over 20 years of experience we’ll ensure you always get the best guidance. We serve a clients at every level of their organization, in whatever capacity we can be most useful, whether as a trusted advisor.</p> </div>");
document.writeln("                  <div class=\'link\'>");
document.writeln("                    <a href=\'#\' class=\'default_link\'>More About us <i class=\'fa fa-angle-right\'></i></a>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("            <!--Footer Column-->");
document.writeln("            <div class=\'footer-column col-lg-4 col-md-6 col-sm-6 col-xs-12\'>");
document.writeln("              <div class=\'footer-widget links-widget\'>");
document.writeln("                <h3 class=\'footer-title\'>主营业务</h3>");
document.writeln("                <div class=\'widget-content\'>");
document.writeln("                  <ul class=\'list\'>");
document.writeln("                    <li><a href=\'service.html\'>机器视觉</a></li>");
document.writeln("                    <li><a href=\'service.html\'>智慧工厂</a></li>");
document.writeln("                    <li><a href=\'service.html\'>智能配套零件</a></li>");
document.writeln("                  </ul>");
document.writeln("                </div>");
document.writeln("");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("            <!--Footer Column-->");
document.writeln("            <div class=\'footer-column col-lg-4 col-md-6 col-sm-6 col-xs-12\'>");
document.writeln("              <div class=\'footer-widget contact-widget\'>");
document.writeln("                <h3 class=\'footer-title\'>联系我们</h3>");
document.writeln("                <div class=\'widget-content\'>");
document.writeln("                  <ul class=\'contact-info\'>");
document.writeln("                    <li><span class=\'icon-signs\'></span>广东省汕头市龙湖区科技西路金霖大厦306</li>");
document.writeln("                    <li><span class=\'icon-phone-call\'></span> Phone: +86-</li>");
document.writeln("                    <li><span class=\'icon-e-mail-envelope\'></span>email@united3.com</li>");
document.writeln("                  </ul>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <!--Footer Column-->");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("");
document.writeln("  <!--Footer Bottom-->");
document.writeln("  <section class=\'footer-bottom\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'pull-left copy-text\'>");
document.writeln("        <p>Copyright &copy; 2018.United3 All rights reserved.</p>");
document.writeln("");
document.writeln("      </div><!-- /.pull-right -->");
document.writeln("      <div class=\'pull-right get-text\'>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\'#\'>Support |  </a></li>");
document.writeln("          <li><a href=\'#\'>Privacy & Policy |</a></li>");
document.writeln("          <li><a href=\'#\'> Terms & Conditions</a></li>");
document.writeln("        </ul>");
document.writeln("      </div><!-- /.pull-left -->");
document.writeln("    </div><!-- /.container -->");
document.writeln("  </section>");
document.writeln("");
document.writeln("</footer>");
document.writeln("");
