document.writeln("    <header class=\'top-bar\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("          <ul class=\'top-bar-info col-md-offset-3 col-sm-offset-3 col-xs-offset-3\'>");
document.writeln("            <li><i class=\'icon-technology\'></i>Phone:(+86) 13829688243</li>");
document.writeln("            <li><i class=\'icon-note2\'></i>info@united3.cn </li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</header>");
document.writeln("");
document.writeln("<section class=\'theme_menu stricky\'>");
document.writeln("  <div class=\'container\'>");
document.writeln("    <div class=\'row\'>");
document.writeln("      <div class=\'col-md-4\'>");
document.writeln("        <div class=\'main-logo\'>");
document.writeln("          <a href=\'index.html\'><img src=\'images/logo/logo43.png\' alt=\'\' width=\'50px;\'></a>");
document.writeln("          <a href=\'index.html\'><img src=\'images/logo/united3.png\' alt=\'\' width=\'50px;\'></a>");
document.writeln("");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <div class=\'col-md-8 menu-column\'>");
document.writeln("        <nav class=\'menuzord\' id=\'main_menu\'>");
document.writeln("          <ul class=\'menuzord-menu\'>");
document.writeln("            <li id=\"index.html\" class=\'active\'><a href=\'index.html\'>首页</a></li>");
document.writeln("            <li id=\'vision.html\'><a href=\'vision.html\'>机器视觉</a></li>");
document.writeln("            <li id=\"index.html\"><a href=\'smartck.html\'>智慧工厂</a></li>");
document.writeln("            <li id=\"index.html\"><a href=\'#.html\'>智能配套零件</a></li>");
document.writeln("            <li id=\"index.html\"><a href=\'#.html\'>新闻中心</a></li>");
document.writeln("            <li><a href=\'#.html\'>关于三合三</a></li>");
document.writeln("          </ul><!-- End of .menuzord-menu -->");
document.writeln("        </nav> <!-- End of #main_menu -->");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("  </div> <!-- End of .conatiner -->");
document.writeln("</section>");
